### PR TITLE
fix bug when jerseyRoot not set

### LINKED ISSUE #26: bug in isJerseyRequest method
https://github.com/palantir/dropwizard-web-security/blob/develop/src/main/java/com/palantir/dropwizard/websecurity/filters/AppSecurityFilter.java#L66

If the default jersey root is `"/"` and the default servlet path will be `""`, then isJerseyRequest will return false.

### PR DESCRIPTION
**Pull request by jmcampanini**
added a test that doesn't modify the `apiRoot`, which exposes an error when determining if a request is a jersey request.

fixes #26

### CODE REVIEW

File: src/test/java/example/Example.java [hunk 1]
```diff
@@ -5,6 +5,7 @@
 package example;
```
Comment (qinfchen) [inline src/test/java/example/Example.java]: package example?

File: src/test/java/example/Example.java [hunk 2]
```diff
@@ -78,7 +86,7 @@ public WebSecurityConfiguration getWebSecurityConfiguration() {
 
         @Override
         public void initialize(Bootstrap<ExampleConfiguration> bootstrap) {
-            bootstrap.addBundle(webSecurityBundle);
+            bootstrap.addBundle(this.webSecurityBundle);
```
Comment (qinfchen) [inline src/test/java/example/Example.java:96]: you use this, but not line 100. please be consistent

File: src/test/java/example/Example.java [hunk 3]
```diff
@@ -86,5 +94,21 @@ public void initialize(Bootstrap<ExampleConfiguration> bootstrap) {
         public void run(ExampleConfiguration configuration, Environment environment) throws Exception {
             environment.jersey().register(new ExampleResource());
         }
+
+        @VisibleForTesting
```
Comment (qinfchen) [inline src/test/java/example/Example.java:105]: this is already in test, why not make this public?

File: src/test/java/example/Example.java [hunk 4]
```diff
@@ -21,19 +22,23 @@
 import javax.ws.rs.Produces;
 import javax.ws.rs.core.MediaType;
 
+/**
+ * Example applications for ETE testing.
+ */
+@SuppressWarnings("checkstyle:designforextension")
```
Comment (qinfchen) [inline src/test/java/example/Example.java:28]: do you need this?

File: src/test/java/example/Example.java (hunk 1 above)
Comment (jmcampanini) [inline src/test/java/example/Example.java]: yup. it's in the test package, so it's never consumed. wanted something that was clearly an example and not production code

File: src/test/java/example/Example.java (hunk 2 above)
Comment (jmcampanini) [inline src/test/java/example/Example.java:96]: fixed

File: src/test/java/example/Example.java (hunk 3 above)
Comment (jmcampanini) [inline src/test/java/example/Example.java:105]: this is the example, i want to call out that it's ONLY for testing purposes and shouldn't be used as part of the example - so don't copy it. i hope the `@VisibleForTesting` would flag that.

File: src/test/java/example/Example.java (hunk 4 above)
Comment (jmcampanini) [inline src/test/java/example/Example.java:28]: yea, because i have classes inside that aren't final AND not abstract. it helps subclass the Web example for the REST example... open to there being a cleaner way, but this should be sufficient

File: src/test/java/example/Example.java (hunk 1 above)
Comment (qinfchen) [inline src/test/java/example/Example.java]: But it lives in the test, why not use same package as the src package? so you don't need to all the imports from the src and it is clearer that this example app is for the src package. 

or you want to be clear that this is an independent app?

File: src/test/java/example/Example.java [hunk 5]
```diff
@@ -58,7 +63,10 @@ public WebSecurityConfiguration getWebSecurityConfiguration() {
         }
     }
 
-    public static final class ExampleApplication extends Application<ExampleConfiguration> {
+    /**
+     * Example Web Application.
+     */
+    public static class ExampleWebApplication extends Application<ExampleConfiguration> {
 
         private final WebSecurityConfiguration webSecurityDefaults = WebSecurityConfiguration.builder()
```
Comment (qinfchen) [inline src/test/java/example/Example.java:78]: can this be moved out of the ExampleWebApplication?

File: src/test/java/example/Example.java (hunk 1 above)
Comment (jmcampanini) [inline src/test/java/example/Example.java]: hrmm. yea, it's serving 2 purposes, but i think you make a good point that it could belong in the same package and having a different one doesn't buy much of anything. moving it to `com.palantir.websecurity.examples`

File: src/test/java/example/Example.java (hunk 3 above)
Comment (qinfchen) [inline src/test/java/example/Example.java:105]: but you are calling getWebSecurityBundle from ExampleRestApplication though... i dont think that is not a good example :(

File: src/test/java/example/Example.java (hunk 5 above)
Comment (jmcampanini) [inline src/test/java/example/Example.java:78]: yes, but it wouldn't be a clear example of how to use this in the common case, which is a web application. i admit it's starting to lose that narrow focus as we add more ETE tests through them, but i use this specific block to generate the README examples

File: src/test/java/example/Example.java [hunk 6]
```diff
@@ -86,5 +94,21 @@ public void initialize(Bootstrap<ExampleConfiguration> bootstrap) {
...
+        @VisibleForTesting
+        WebSecurityBundle getWebSecurityBundle() {
+            return this.webSecurityBundle;
+        }
+    }
+
+    /**
+     * Example REST Application.
+     */
+    public static final class ExampleRestApplication extends ExampleWebApplication {
```
Comment (qinfchen) [inline src/test/java/example/Example.java:115]: can this be its own separate app instead of extending the "web" app for  "rest" app?

File: src/test/java/com/palantir/websecurity/examples/Example.java [hunk 7]
```diff
@@ -58,7 +69,11 @@ public WebSecurityConfiguration getWebSecurityConfiguration() {
         }
     }
 
-    public static final class ExampleApplication extends Application<ExampleConfiguration> {
+    /**
+     * Example Web Application. Sets application defaults using {@link #webSecurityDefaults}. The application is
+     * configured to server assets from `/*` and Jersey API requests from `/api/*`.
```
Comment (qinfchen) [inline src/test/java/com/palantir/websecurity/examples/Example.java]: serve?

**Comment by qinfchen** [comment]
:+1:
